# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import photograft_pb2 as photograft__pb2


class PhotograftServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMask = channel.unary_unary(
                '/photograftai.PhotograftService/GetMask',
                request_serializer=photograft__pb2.MaskRequest.SerializeToString,
                response_deserializer=photograft__pb2.MaskResponse.FromString,
                )


class PhotograftServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhotograftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMask,
                    request_deserializer=photograft__pb2.MaskRequest.FromString,
                    response_serializer=photograft__pb2.MaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photograftai.PhotograftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhotograftService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/photograftai.PhotograftService/GetMask',
            photograft__pb2.MaskRequest.SerializeToString,
            photograft__pb2.MaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
