# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: photograft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10photograft.proto\x12\x0cphotograftai\",\n\x0bMaskRequest\x12\r\n\x05image\x18\x01 \x01(\t\x12\x0e\n\x06points\x18\x02 \x01(\x0c\"\x1d\n\x0cMaskResponse\x12\r\n\x05masks\x18\x01 \x03(\t2W\n\x11PhotograftService\x12\x42\n\x07GetMask\x12\x19.photograftai.MaskRequest\x1a\x1a.photograftai.MaskResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photograft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MASKREQUEST._serialized_start=34
  _MASKREQUEST._serialized_end=78
  _MASKRESPONSE._serialized_start=80
  _MASKRESPONSE._serialized_end=109
  _PHOTOGRAFTSERVICE._serialized_start=111
  _PHOTOGRAFTSERVICE._serialized_end=198
# @@protoc_insertion_point(module_scope)
